### ISSUE TITLE
-s not working

### ISSUE THREAD

**Issue by slicken** [ralscha/hibp-passwords-downloader#1]
hi,

the single file option is not working.
it downloads the passwords in a directory and saves them in many files as it do without the -s option.
otherwise its working nicely

**Comment by ralscha** [comment]
Hi.
Yes. That's the idea. It should first download the passwords into multiple files and at the end it should merge them into one file and delete the individual files. This way the program is able to resume the download if it crashes or it looses connection to the internet.

I need to test it today. Maybe the merge at the end does not work.

**Comment by ralscha** [comment]
Tested it. The merge does work. But the resume did not work for single file. 
I created a new release (0.2.0).

Like before the -s downloads the individual files. It stores them in the .hibp_<filename> folder and at the end it merges them together into <filename> and deletes the temporary folder

```
./hibp-passwords-downloader -s single
```

When the download fails resume it with
```
./hibp-passwords-downloader -s single -r
```

**Comment by slicken** [comment]
closing
